#!/bin/bash
echo "=== Self-Evolution Services ==="
grep "Self-Evolution" /opt/openaide/server.log 2>/dev/null || echo "No Self-Evolution logs"
echo ""
echo "=== Skill Discovery ==="
grep "SkillDiscovery" /opt/openaide/server.log 2>/dev/null || echo "No SkillDiscovery logs"
echo ""
echo "=== Pattern Detector ==="
grep "PatternDetector" /opt/openaide/server.log 2>/dev/null || echo "No PatternDetector logs"
echo ""
echo "=== Feedback Collector ==="
grep "FeedbackCollector" /opt/openaide/server.log 2>/dev/null || echo "No FeedbackCollector logs"
echo ""
echo "=== Memory Extract ==="
grep "MemoryExtract" /opt/openaide/server.log 2>/dev/null || echo "No MemoryExtract logs"
echo ""
echo "=== Context Engine ==="
grep "Context engine" /opt/openaide/server.log 2>/dev/null || echo "No Context engine logs"
echo ""
echo "=== Memory Semantic ==="
grep "Semantic search" /opt/openaide/server.log 2>/dev/null || echo "No Semantic search logs"
echo ""
echo "=== Process Info ==="
ps aux | grep openaide-server | grep -v grep
