#!/usr/bin/env python3
import requests,json
BASE="http://localhost:19375/api"
print("1. Slash commands:")
r=requests.get(f"{BASE}/slash/commands",timeout=5)
print(f"  Status: {r.status_code}")
print(f"  Body: {r.text[:500]}")
print()
print("2. Slash execute /help:")
r=requests.post(f"{BASE}/slash/execute",json={"command":"help","args":"","session_id":"test"},timeout=5)
print(f"  Status: {r.status_code}")
print(f"  Body: {r.text[:500]}")
print()
print("3. Slash execute /agent build:")
r=requests.post(f"{BASE}/slash/execute",json={"command":"agent","args":"build","session_id":"test"},timeout=5)
print(f"  Status: {r.status_code}")
print(f"  Body: {r.text[:300]}")
print()
print("4. Agent routing routes:")
r=requests.get(f"{BASE}/agent-routing/routes",timeout=5)
print(f"  Status: {r.status_code}")
print(f"  Body: {r.text[:300]}")
print()
print("5. Agent routing route/build:")
r=requests.get(f"{BASE}/agent-routing/route/build",timeout=5)
print(f"  Status: {r.status_code}")
print(f"  Body: {r.text[:300]}")
