package main

import (
	"fmt"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"time"
)

// cmdSetup runs an interactive configuration wizard.
func cmdSetup() {
	runSetupTUI()
}

// setupResult 向导收集的配置
type setupResult struct {
	lang       string // "zh" / "en"
	provider   string // 显示名
	baseURL    string
	apiKey     string
	model      string
	flashModel string
	searchURL  string
}

// writeSetupFiles 生成 config.yaml 与默认 prompt 文件
func writeSetupFiles(cfg setupResult) (configPath, promptsDir string, err error) {
	sb := new(strings.Builder)
	sb.WriteString("# OpenAIDE Configuration — generated by setup wizard\n")
	sb.WriteString(fmt.Sprintf("# %s\n\n", time.Now().Format("2006-01-02 15:04:05")))
	sb.WriteString(fmt.Sprintf("lang: %s\n\n", cfg.lang))
	sb.WriteString("server:\n  host: 0.0.0.0\n  port: 8080\n\n")
	sb.WriteString("llm:\n  providers:\n")
	name := strings.ToLower(strings.Split(cfg.provider, " ")[0])
	sb.WriteString(fmt.Sprintf("    - name: %s\n", name))
	sb.WriteString("      type: openai\n")
	sb.WriteString(fmt.Sprintf("      base_url: %s\n", cfg.baseURL))
	if cfg.apiKey != "" {
		sb.WriteString(fmt.Sprintf("      api_key: %s\n", cfg.apiKey))
	}
	sb.WriteString(fmt.Sprintf("      default_model: %s\n", cfg.model))
	sb.WriteString("      timeout: 300\n      thinking: true\n\n")
	if cfg.flashModel != "" && cfg.flashModel != cfg.model {
		sb.WriteString(fmt.Sprintf("    - name: %s-flash\n", name))
		sb.WriteString("      type: openai\n")
		sb.WriteString(fmt.Sprintf("      base_url: %s\n", cfg.baseURL))
		if cfg.apiKey != "" {
			sb.WriteString(fmt.Sprintf("      api_key: %s\n", cfg.apiKey))
		}
		sb.WriteString(fmt.Sprintf("      default_model: %s\n", cfg.flashModel))
		sb.WriteString("      timeout: 120\n\n")
		sb.WriteString("  model_routing:\n")
		sb.WriteString(fmt.Sprintf("    reasoning: %s\n", cfg.model))
		sb.WriteString(fmt.Sprintf("    execution: %s\n\n", cfg.flashModel))
	}
	sb.WriteString(fmt.Sprintf("storage:\n  data_dir: %s\n  session_store: sqlite\n\n", os.Getenv("HOME")+"/.openaide/data"))
	sb.WriteString("log:\n  level: info\n  persist: false\n\n")
	if cfg.searchURL != "" {
		sb.WriteString(fmt.Sprintf("search:\n  searxng_url: %s\n", cfg.searchURL))
	}

	configPath = os.Getenv("HOME") + "/.openaide/config.yaml"
	os.MkdirAll(filepath.Dir(configPath), 0755)
	if err = os.WriteFile(configPath, []byte(sb.String()), 0600); err != nil {
		return "", "", err
	}

	langSuffix := "en"
	if cfg.lang == "zh" {
		langSuffix = "zh"
	}
	promptsDir = os.Getenv("HOME") + "/.openaide/data/prompts"
	os.MkdirAll(promptsDir, 0755)
	defaultPrompts := map[string]string{
		"l0.md":          defaultL0(langSuffix),
		"l3_coding.md":   defaultL3Coding(langSuffix),
		"l3_review.md":   defaultL3Review(langSuffix),
		"l3_teaching.md": defaultL3Teaching(langSuffix),
		"l3_research.md": defaultL3Research(langSuffix),
	}
	for name, content := range defaultPrompts {
		path := filepath.Join(promptsDir, name)
		if _, err := os.Stat(path); os.IsNotExist(err) {
			os.WriteFile(path, []byte(content), 0644)
		}
	}
	return configPath, promptsDir, nil
}

func defaultL0(lang string) string {
	if lang == "zh" {
		return `你是 OpenAIDE，一个多功能的 AI 编程助手。

## 核心原则
- 根据任务切换角色：程序员、审查者、研究者、教师
- 不确定时查阅，不要猜测
- 超出能力时承认并建议替代方案
- 复杂任务先规划，简单问题直接回答

## 输出质量
- 分析代码时必须给出具体改进建议，包含文件名和行号
- 不要只指出问题——要提出解决方案
- 审查代码时说清楚：改什么、在哪个文件改、为什么

## 安全
- 执行破坏性命令前必须确认
- 不要修改项目目录外的文件
- 文件写入和命令执行需要审批`
	}
	return `You are OpenAIDE, a versatile AI coding assistant.

## Core
- Adapt to the task: programmer, reviewer, researcher, teacher.
- If unsure: look it up. Don't guess.
- Complex tasks: plan first. Simple questions: answer directly.

## Output Quality
- When analyzing code, provide concrete suggestions with file names and line numbers.
- Don't just point out problems — propose solutions.
- Analysis without actionable recommendations is incomplete.

## Safety
- Never execute destructive commands without explicit confirmation.
- Never modify files outside the project directory.`
}

func defaultL3Coding(lang string) string {
	if lang == "zh" {
		return `## 编码模式
- 遵循项目已有的编码规范和模式。
- 显式处理错误，永远不要静默吞掉异常。
- 适当时为新功能添加测试。
- 不引入与项目风格不一致的新写法。`
	}
	return `## Coding Mode
- Write clean, idiomatic code following existing project conventions.
- Handle errors explicitly. Never swallow errors silently.
- Add tests for new functionality when appropriate.
- Use the project's existing patterns — don't introduce new styles.`
}

func defaultL3Review(lang string) string {
	if lang == "zh" {
		return `## 审查模式
- 检查：正确性、安全性、性能、可读性、边界条件。
- 声称"缺少"之前先验证——很多处理在调用方而非当前函数中。
- 发现潜在问题时给出具体改进建议。
- 关注：SQL注入、XSS、竞态条件、空指针、资源泄漏。`
	}
	return `## Review Mode
- Check: correctness, security, performance, readability, edge cases.
- Verify before reporting "missing" — many guards are in callers, not the function itself.
- Flag potential issues with concrete suggestions.
- Look for: SQL injection, XSS, race conditions, nil pointers, resource leaks.`
}

func defaultL3Teaching(lang string) string {
	if lang == "zh" {
		return `## 教学模式
- 先用清晰简洁的语言解释核心概念。
- 使用示例和类比来帮助理解。
- 解释"为什么"而不仅仅是"怎么做"。
- 结构：概念 → 示例 → 深入细节（如需）。`
	}
	return `## Teaching Mode
- Lead with a clear, simple explanation.
- Use examples and analogies where helpful.
- Answer the "why" — not just the "how".
- Structure: concept → example → deeper details (if needed).`
}

func defaultL3Research(lang string) string {
	if lang == "zh" {
		return `## 研究模式
- 先收集信息，再形成结论。
- 声称"缺少 X"或"X 不安全"之前，先搜索 X 是否在代码库其他地方已经存在。
- 不要不检查调用链就报告"缺少"。
- 结尾给出可执行的行动计划：先做什么、预估工作量。`
	}
	return `## Research Mode
- Gather information before forming conclusions.
- Before claiming "X is missing" or "X is unsafe": search for X elsewhere in the codebase first.
- Never report "missing" without checking the call chain.
- End with a concrete action plan with estimated effort.`
}

func testConnection(baseURL, apiKey, model string) bool {
	client := &http.Client{Timeout: 10 * time.Second}
	body := strings.NewReader(fmt.Sprintf(`{"model":"%s","messages":[{"role":"user","content":"hi"}],"max_tokens":5}`, model))
	req, _ := http.NewRequest("POST", baseURL+"/chat/completions", body)
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Authorization", "Bearer "+apiKey)
	resp, err := client.Do(req)
	if err != nil {
		return false
	}
	resp.Body.Close()
	return resp.StatusCode == 200
}
