package main

import (
	"fmt"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/pterm/pterm"
)

// cmdSetup runs an interactive configuration wizard.
func cmdSetup() {
	pterm.DefaultBox.WithTitle("OpenAIDE Setup Wizard").Println(
		"This wizard will help you configure OpenAIDE.\n" +
			"No prior knowledge required — just answer a few questions.")

	fmt.Println()

	// Step 1: Language
	lang, _ := pterm.DefaultInteractiveSelect.
		WithOptions([]string{"中文", "English"}).
		WithDefaultText("Choose language / 选择语言:").
		Show()

	// Step 2: Provider
	type providerOption struct {
		name     string
		baseURL  string
		needModel bool
	}
	providers := []providerOption{
		{name: "DeepSeek (recommended)", baseURL: "https://api.deepseek.com/v1", needModel: false},
		{name: "OpenAI", baseURL: "https://api.openai.com/v1", needModel: false},
		{name: "Anthropic", baseURL: "https://api.anthropic.com", needModel: false},
		{name: "Ollama (local)", baseURL: "http://localhost:11434/v1", needModel: true},
		{name: "Custom OpenAI-compatible", baseURL: "", needModel: true},
	}
	var opts []string
	for _, p := range providers {
		opts = append(opts, p.name)
	}
	choice, _ := pterm.DefaultInteractiveSelect.
		WithOptions(opts).
		WithDefaultText("Choose your LLM provider:").
		Show()

	var provider providerOption
	for _, p := range providers {
		if p.name == choice {
			provider = p
			break
		}
	}

	// Step 3: API Key
	var apiKey string
	if provider.name != "Ollama (local)" {
		keyHint := "Enter your API key (will be saved to ~/.openaide/config.yaml):"
		if strings.Contains(provider.name, "DeepSeek") {
			keyHint = "Enter your DeepSeek API key (get one at https://platform.deepseek.com):"
		} else if strings.Contains(provider.name, "OpenAI") {
			keyHint = "Enter your OpenAI API key (get one at https://platform.openai.com):"
		} else if strings.Contains(provider.name, "Anthropic") {
			keyHint = "Enter your Anthropic API key (get one at https://console.anthropic.com):"
		}
		apiKey, _ = pterm.DefaultInteractiveTextInput.
			WithDefaultText(keyHint).
			WithMask("*").
			Show()
		if apiKey == "" {
			pterm.Warning.Println("No API key provided. You can add it later in ~/.openaide/config.yaml")
		}
	}

	// Step 4: Custom base URL
	customURL := provider.baseURL
	if provider.baseURL == "" {
		customURL, _ = pterm.DefaultInteractiveTextInput.
			WithDefaultText("Enter the base URL for your OpenAI-compatible API:").
			WithDefaultValue("https://api.example.com/v1").
			Show()
	}

	// Step 5: Model selection
	model := "deepseek-v4-pro"
	flashModel := "deepseek-v4-flash"
	if provider.needModel {
		model, _ = pterm.DefaultInteractiveTextInput.
			WithDefaultText("Enter your reasoning model name:").
			WithDefaultValue("gpt-4o").
			Show()
		flashModel, _ = pterm.DefaultInteractiveTextInput.
			WithDefaultText("Enter your fast/execution model (or press Enter to use same):").
			WithDefaultValue(model).
			Show()
	}

	// Step 6: Optional SearXNG
	pterm.Info.Println("Web search is optional but recommended for better results.")
	useSearch, _ := pterm.DefaultInteractiveConfirm.
		WithDefaultText("Configure SearXNG for web search?").
		WithDefaultValue(false).
		Show()
	searchURL := ""
	if useSearch {
		searchURL, _ = pterm.DefaultInteractiveTextInput.
			WithDefaultText("Enter your SearXNG instance URL:").
			WithDefaultValue("http://localhost:8888").
			Show()
	}

	// Generate config
	configPath := os.Getenv("HOME") + "/.openaide/config.yaml"
	os.MkdirAll(filepath.Dir(configPath), 0755)

	sb := new(strings.Builder)
	sb.WriteString("# OpenAIDE Configuration — generated by setup wizard\n")
	sb.WriteString(fmt.Sprintf("# %s\n\n", time.Now().Format("2006-01-02 15:04:05")))
	sb.WriteString(fmt.Sprintf("lang: %s\n\n", map[bool]string{true: "zh", false: "en"}[lang == "中文"]))
	sb.WriteString(fmt.Sprintf("server:\n  host: 0.0.0.0\n  port: 8080\n\n"))
	sb.WriteString(fmt.Sprintf("llm:\n"))
	sb.WriteString(fmt.Sprintf("  providers:\n"))
	sb.WriteString(fmt.Sprintf("    - name: %s\n", strings.ToLower(strings.Split(provider.name, " ")[0])))
	sb.WriteString(fmt.Sprintf("      type: openai\n"))
	sb.WriteString(fmt.Sprintf("      base_url: %s\n", customURL))
	if apiKey != "" {
		sb.WriteString(fmt.Sprintf("      api_key: %s\n", apiKey))
	}
	sb.WriteString(fmt.Sprintf("      default_model: %s\n", model))
	sb.WriteString(fmt.Sprintf("      timeout: 300\n"))
	sb.WriteString(fmt.Sprintf("      thinking: true\n\n"))
	if flashModel != "" && flashModel != model {
		sb.WriteString(fmt.Sprintf("    - name: %s-flash\n", strings.ToLower(strings.Split(provider.name, " ")[0])))
		sb.WriteString(fmt.Sprintf("      type: openai\n"))
		sb.WriteString(fmt.Sprintf("      base_url: %s\n", customURL))
		if apiKey != "" {
			sb.WriteString(fmt.Sprintf("      api_key: %s\n", apiKey))
		}
		sb.WriteString(fmt.Sprintf("      default_model: %s\n", flashModel))
		sb.WriteString(fmt.Sprintf("      timeout: 120\n\n"))
		sb.WriteString(fmt.Sprintf("  model_routing:\n"))
		sb.WriteString(fmt.Sprintf("    reasoning: %s\n", model))
		sb.WriteString(fmt.Sprintf("    execution: %s\n\n", flashModel))
	}
	sb.WriteString(fmt.Sprintf("storage:\n  data_dir: %s\n  session_store: sqlite\n\n", os.Getenv("HOME")+"/.openaide/data"))
	sb.WriteString(fmt.Sprintf("log:\n  level: info\n  persist: false\n\n"))
	if searchURL != "" {
		sb.WriteString(fmt.Sprintf("search:\n  searxng_url: %s\n", searchURL))
	}

	if err := os.WriteFile(configPath, []byte(sb.String()), 0600); err != nil {
		pterm.Error.Println("Failed to write config:", err)
		return
	}

	pterm.Success.Printfln("Configuration saved to %s", configPath)
	fmt.Println()

	// Step 7: Test connection
	if apiKey != "" {
		pterm.Info.Println("Testing connection to your LLM provider...")
		spinner, _ := pterm.DefaultSpinner.Start("Connecting...")
		ok := testConnection(customURL, apiKey, model)
		spinner.Stop()
		if ok {
			pterm.Success.Println("Connection successful! Your LLM provider is ready.")
		} else {
			pterm.Warning.Println("Could not connect to LLM provider. Check your API key and network.")
			pterm.Warning.Println("You can test manually: openaide \"hello\"")
		}
	}

	fmt.Println()
	pterm.DefaultBox.WithTitle("Setup Complete").Println(
		"Run 'openaide' to start chatting.\n" +
			"Run 'openaide --help' to see all options.\n" +
			fmt.Sprintf("Config file: %s", configPath))
}

func testConnection(baseURL, apiKey, model string) bool {
	client := &http.Client{Timeout: 10 * time.Second}
	body := strings.NewReader(fmt.Sprintf(`{"model":"%s","messages":[{"role":"user","content":"hi"}],"max_tokens":5}`, model))
	req, _ := http.NewRequest("POST", baseURL+"/chat/completions", body)
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Authorization", "Bearer "+apiKey)
	resp, err := client.Do(req)
	if err != nil {
		return false
	}
	resp.Body.Close()
	return resp.StatusCode == 200
}
